### ISSUE TITLE
[Bug] go build ./... failed

### ISSUE THREAD

**Issue by g41797** [memphisdev/memphis.go#124] opened 2023-09-12 07:51 UTC
go build ./... failed with errors:
```bash
examples/producer.go:10:6: main redeclared in this block
        examples/consumer.go:12:6: other declaration of main
```

Wrong folders organization

**Comment by idanasulinmemphis** [comment] 2023-10-18 07:35
This happens since we have the examples scripts, by design it is ok.
Closing this one

**Closed by idanasulinmemphis** 2023-10-18 07:35 UTC
